ideaTracker/urls.py
from django.conf.urls import url

from . import views

app_name = 'ideaTracker'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'add', views.add, name='add'),
    url(r'edit/([0-9]+)/$', views.edit, name='edit'),
    url(r'^(?P<idea_id>[0-9]+)/$', views.detail, name='detail'),
]

idea_tracker/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^ideaTracker/', include('ideaTracker.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ideaTracker/models.py
from django.db import models

# Create your models here.
class Idea(models.Model):
    priority = models.IntegerField(default=9)
    title = models.CharField(max_length=140)
    description = models.CharField(max_length=500)
    status = models.IntegerField(default=0)
    state = models.IntegerField(default=0)
    create_date = models.DateTimeField(auto_now_add=True, blank=True)
    modified_date = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return self.title

ideaTracker/forms.py
from django import forms

class AddForm(forms.Form):
    title = forms.CharField(label='Title', max_length=40)
    description = forms.CharField(label='Description', max_length=140)
    PriorityChoices = ((1, 'Low'), (2, 'Medium'), (3, 'High'))
    priority = forms.ChoiceField(label='Priority', choices=PriorityChoices, initial=1)

# TODO can make this inherit from add form?
class EditForm(forms.Form):
    title = forms.CharField(label='Title', max_length=40)
    description = forms.CharField(label='Description', max_length=140)

ideaTracker/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader

from .models import Idea
from .forms import AddForm, EditForm
from .utils  import IdeaState, getStatesInDict
from datetime import datetime

# Index page showing list of ideas added
def index(request):
    # get all ideas ordered by priority from db
    idea_list = Idea.objects.all().order_by('priority')
    # get the template used to display the items
    template = loader.get_template('ideaTracker/index.html')
    # context passed to the template
    context = {
        'idea_list': idea_list,
    }
    return HttpResponse(template.render(context, request));

# View to add an idea
def add(request):
    # if we came here by post request, user has filled the add form
    if request.method == 'POST':
        # get the form from request 
        form = AddForm(request.POST)
        # check if form is valid
        if form.is_valid():
            # get form data 
            title       = form.cleaned_data['title']
            description = form.cleaned_data['description']
            priority    = form.cleaned_data['priority']
            # add the idea in the db
            Idea.objects.create(title = title,
                                description = description,
                                state = IdeaState.NEW.value,
                                priority = priority)
            # redirect user to idea list page  
            return HttpResponseRedirect('/ideaTracker/')
        """
        try:
            title    = request.POST['title']
            desc     = request.POST['desc']
            priority = request.POST['priority']
        except (KeyError):
            return HttpResponse("Please fill all data")
        else:
            #TODO make a function in utils to validated input and add
            Idea.objects.create(title = title, description = desc, state=IdeaState.NEW.value, priority = priority)
            return HttpResponseRedirect('/ideaTracker/')
        """        
    else:
        # we came here by get request, show the user the add form
        form = AddForm()
        return render(request, 'ideaTracker/add.html', {'form' : form})

# View to edit an idea        
def edit(request, idea_id):
    # if we came here via post request  
    if request.method == 'POST':
        if 'save' in request.POST:
            # get the form from request 
            form = EditForm(request.POST)
            # check if form is valid
            if form.is_valid():
                # get form data 
                title       = form.cleaned_data['title']
                description = form.cleaned_data['description']

            #TODO Put safety or move to common function for form validation
            state   = request.POST['state']

            # update idea in db
            Idea.objects.filter(pk=idea_id).update(title = title,
                                                   description = description,
                                                   state=state,
                                                   modified_date=datetime.now())
            return HttpResponseRedirect('/ideaTracker/')
        elif 'cancel' in request.POST:
            return HttpResponseRedirect('/ideaTracker/')
        else:
            return HttpResponse("Somethings wrong")
    else:
        # get idea from db
        idea = Idea.objects.get(pk=idea_id) 
        # get idea states. TODO any other way for this?
        ideaStates = getStatesInDict()
        # create form data
        formData = {'title' : idea.title, 'description' : idea.description}
        # create form
        form = EditForm(formData)
        return render(request, 'ideaTracker/edit.html', {'form' : form, 'idea': idea, 'ideaStates': ideaStates})

# Detailed view of an idea
def detail(request, idea_id):
    if request.method == 'POST':
        if 'delete' in request.POST:
                Idea.objects.filter(pk=idea_id).delete()
                return HttpResponseRedirect('/ideaTracker/')
        else:
            return HttpResponse("Something's wrong")
    else:    
        try:
            idea = Idea.objects.get(pk=idea_id)
        except Idea.DoesNotExist:
            raise Http404("Idea does not exist");
        return render(request, 'ideaTracker/detail.html', {'idea': idea, 'state': IdeaState(idea.state).name})

ideaTracker/templates/ideaTracker/add.html
<header style="background-color: none; text-align:center">
<h1>Idea Tracker</h1>
</header>
<h1>Add Idea</h1>

<form action="{% url 'ideaTracker:add'" method="post">
{% csrf_token %}
{{ form.as_table }}
<input type="submit" value="ADD">
</form>

ideaTracker/templates/ideaTracker/detail.html
<header style="background-color: none; text-align:center">
<h1>Idea Tracker</h1>
</header>
<h1>{{ idea.title }}</h1>

<h2>{{ idea.description }} </h2>
<p>Current state : {{ state }} </p>
<p>Current Priority : {{ idea.priority }} </p>
<p>Created on : {{ idea.create_date }} </p>
<p>Last modified on : {{ idea.modified_date }} </p>

<form action="{% url 'ideaTracker:edit' idea.id %}">
{% csrf_token %}
<input type="submit" name="edit" value="Edit" />
</form>
<form method="post">
{% csrf_token %}
<input type="hidden" name="idea_id" value="{{ idea.id }}"/>
<input type="submit" value="Delete" name="delete"/>
</form>

ideaTracker/templates/ideaTracker/edit.html
<header style="background-color: none; text-align:center">
<h1>Idea Tracker</h1>
</header>
<form action="{% url 'ideaTracker:edit' idea.id %}" method="post">
{% csrf_token %}
{{ form }}
<p> State
    <select name="state">
    {% for key, value in ideaStates.items %}
        <option {% if key == idea.state %} selected="selected" {% endif %} {% if key < idea.state %} disabled {% endif %} value="{{ key }}">{{ value }}</option>
        {% endfor %}
    </select>
</p>    
<input type="hidden" name="idea_id" value="{{ idea.id }}"/>
<input type="submit" name="save" value="Save"/>
<input type="submit" name="cancel" value="Cancel"/>
</form>

ideaTracker/templates/ideaTracker/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'ideaTracker/css/core.css' %}">
<header style="background-color: none; text-align:center">
<h1>Idea Tracker</h1>
</header>
{% if idea_list %}
    <table style="width:100%;padding-left:40px;padding-bottom:40px;">
    <tr>
    <td><h2> Idea List </h2></td>
    </tr>
    <tr>
        <td><b>Title</b></td>
        <td><b>Description</b></td>
    </tr>
    {% for idea in idea_list %}
    <tr>
        <td><a href="{% url 'ideaTracker:detail' idea.id %}">{{ idea.title }}</a></td>
        <td>{{ idea.description }}</td>
    </tr>
    {% endfor %}
    </table>
{% else %}    
    <p>No ideas added yet.</p>
{% endif %}

<form action="{% url 'ideaTracker:add' %}">
{% csrf_token %}
    <input type="submit" value="Add more ideas"/>
</form>    

<footer style="position:fixed; bottom:0; text-align:center; width:100%">
<p> Under development </p>
</footer>